### ISSUE TITLE
python check_env.py output

### ISSUE THREAD

**Issue by ericgcoker** [mmckerns/tuthpc#8]
I'm using Anaconda2-4.1.0-Linux-x86_64.sh on Centos6 64bit. Should I be using 32 bit Python to avoid this error when I run "python check_env.py" and receive this output?

pyina:: Executable 'ezpool.py' not found
pyina:: Executable 'ezscatter.py' not found
pathos:: Executable 'pathos_tunnel.py' not found
pathos:: Executable 'pathos_server.py' not found
pathos:: Executable 'tunneled_pathos_server.py' not found

**Comment by mmckerns** [comment]
@bears34egc: Hmm. I don't think 63-bit versus 32-bit matters. Let's start with first things first…
Is this the only output you are receiving?  (I assume you have `pathos` and `pyina` installed).  What version of python are you using (I assume roughly the latest 2.7)?  Are these executables actually installed (you can check from the terminal console like this: `pox_launcher.py "which('ezpool.py')"` ), or if that doesn't work for some reason, then try `which ezpool.py`.

**Comment by ericgcoker** [comment]
I had issue installing the pyina and pathos correctly with git. I just downloaded and installed from source with setup.py files. And the check_env.py script now runs with no issues.

**Comment by mmckerns** [comment]
Ok, I'm glad you solved it.
